routes/web.php
use App\Http\Controllers\frontend\StudentCourseEnroll;
use App\Http\Controllers\frontend\StudentAccountController;
use App\Http\Controllers\admin\AdminLoginController;
use App\Http\Controllers\frontend\StudentMeetRequestController;
use App\Http\Controllers\admin\SlackController;
use App\Http\Controllers\admin\ExamQuestionController;
use App\Http\Controllers\admin\QuizQuestionController;
use App\Http\Controllers\admin\StudentExamController;
use App\Http\Controllers\admin\StudentQuizController;
use App\Http\Controllers\admin\StudentCertificateController;
use App\Http\Controllers\admin\UserManageController;
use App\Http\Controllers\admin\VideoController;
use App\Http\Controllers\admin\CompanyController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\admin\SystemSettingController;
use App\Http\Controllers\admin\PermissionController;
use App\Http\Controllers\admin\StuentRecordVideo;
use App\Http\Controllers\admin\NoticeController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\Auth\ResetPasswordController;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [FrontendController::class, 'index'])->name('home_route');
Route::get('/panel-student-course', [FrontendController::class, 'studentPanelCourse'])->name('p_s_c_route');
Route::get('/panel-student-course-details/{id}', [FrontendController::class, 'studentPanelCourseDetails'])->name('p_s_c_d_route');
Route::get('/panel-student-course-sylabus/{id}', [FrontendController::class, 'courseSylabus'])->name('c_s');


Route::get('/user-registration', [FrontendController::class, 'userRegistration'])->name('u_r');
Route::get('/user-reset-password', [FrontendController::class, 'userResetPassword'])->name('u_r_p');
Route::post('/user-reset-password-post', [FrontendController::class, 'userResetPasswordPost'])->name('u_r_p_post');
Route::get('/get-exam-result/{course_id}', [FrontendController::class, 'getExamResult'])->name('get_exam_result');
Route::get('/get-quiz-result/{course_id}', [FrontendController::class, 'getQuizResult'])->name('get_quiz_result');


Route::get('/panel-student-course-class-news/{id}', [FrontendController::class, 'classNews'])->name('c_n');
Route::get('/panel-student-course-recording/{id}', [FrontendController::class, 'courseRecording'])->name('c_r');
Route::get('/panel-student-course-test-quiz/{id}', [FrontendController::class, 'courseTestAndQuiz'])->name('c_t_q');
Route::get('/panel-student-course-meet-teacher/{id}', [FrontendController::class, 'courseMeetTeacher'])->name('c_m_t');


Route::get('/panel-student-course-payment-invoice/{id}', [FrontendController::class, 'coursePaymentInvoice'])->name('c_p_i');
Route::get('/panel-student-course-quiz/{course_id}/{quiz_id}', [FrontendController::class, 'courseQuiz'])->name('c_q');
Route::get('/panel-student-course-test/{course_id}/{test_id}', [FrontendController::class, 'courseTest'])->name('c_t');
Route::get('/panel-student-meet-teacher/{course_id}', [FrontendController::class, 'courseMeetTeacher'])->name('m_t');


Route::get('/panel-student-chat/{id}', [FrontendController::class, 'chatStudent'])->name('chat_student');
Route::get('/panel-student-chat-message/{id}/{course_id}', [FrontendController::class, 'chatStudentMessage'])->name('chat_student_message');
Route::get('/all-video', [FrontendController::class, 'allVideo'])->name('all_video_route');
Route::get('/about', [FrontendController::class, 'about'])->name('about_route');


Route::get('/announcement/list', [FrontendController::class, 'announcement'])->name('announcement_route');
Route::get('/contact', [FrontendController::class, 'contact'])->name('contact_route');
Route::get('/all-course', [FrontendController::class, 'allCourse'])->name('all_course_route');
Route::get('/faq', [FrontendController::class, 'faq'])->name('faq_route');


Route::get('/stu-record-video', [FrontendController::class, 'recordVideo'])->name('record_video_route');
Route::get('/course-details/{id}', [FrontendController::class, 'show'])->name('course_details');
Route::get('student-course-enroll', [StudentCourseEnroll::class, 'enrollNow'])->name('course_enroll_route');
Route::post('contact-store', [ContactController::class, 'contactStore'])->name('contact_store_route');


Route::get('password/reset/{token}', [ResetPasswordController::class, 'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class, 'reset'])->name('password.update');


Route::resource('student-course-enroll', StudentCourseEnroll::class);

Route::group(['middleware' => 'auth'], function () {

    Route::resource('meet-instructor', StudentMeetRequestController::class);
    Route::get('student-certificate-view', [StudentMeetRequestController::class, 'certificate'])->name('s_certificate');
    Route::post('student-certificate-data', [StudentMeetRequestController::class, 'certificateData'])->name('s_certificate_d');
    Route::get('/exam/q/delete/{id}', [ExamController::class, 'examQDelete'])->name('exam_q_delete');

    Route::get('/quiz/q/delete/{id}', [QuizController::class, 'quizQDelete'])->name('quiz_q_delete');
    Route::get('/join/call', [SlackController::class, 'joinCall'])->name('video_call');
    Route::get('/slack/message/{id}', [SlackController::class, 'slackMessage'])->name('channel_message_route');
    Route::post('/slack/channel/store', [SlackController::class, 'channelStore'])->name('channel_route_store');

    Route::get('ajax/{id}', [SlackController::class, 'slackMessageAjax'])->name('cchannel_message_route_ajax');
    Route::post('data/ajax/store', [SlackController::class, 'slackMessageAjaxStore'])->name('a_message_route_store');
    Route::get('admin/dashboard', [AdminController::class, 'index'])->name('admin.dashboard');
    Route::get('cc-course-student/{courseId}', [StudentCertificateController::class, 'courseStudent']);


    Route::post('certificate-student-generate', [StudentCertificateController::class, 'generateCertificate'])->name('certificate_generate');
    Route::post('certificate-student-generate-quiz', [StudentCertificateController::class, 'generateCertificateQuiz'])->name('certificate_generate_quiz');

    Route::get('get-teacher/{role_id}', [UserManageController::class,'getTeacher'])->name('get_teacher');
    Route::get('get-student/{role_id}', [UserManageController::class,'getStudent'])->name('get_student');

    Route::group(['middleware' => 'role'], function () {

        Route::resource('notice', NoticeController::class);
        Route::resource('record-video', StuentRecordVideo::class);
        Route::resource('contact-student', ContactController::class);
        Route::resource('exam', ExamController::class);



        Route::resource('question-exam', ExamQuestionController::class);
        Route::resource('question-quiz', QuizQuestionController::class);
        Route::resource('video', VideoController::class);
        Route::resource('company', CompanyController::class);


        Route::get('/permission-list', [PermissionController::class, 'index'])->name('permission_list');
        Route::get('/permission-edit/{id}', [PermissionController::class, 'edit'])->name('permission_edit');
        Route::PATCH('/permission-update/{id}', [PermissionController::class, 'update'])->name('permission_update');
        Route::resource('manage-user', UserManageController::class);



        Route::resource('roles', RoleController::class);
        Route::resource('role_permissions', RolePermissionController::class)->only(['index', 'create', 'store', 'destroy']);
        Route::resource('course-category', CourseCategoryController::class);
        Route::resource('course', CourseController::class);


        Route::resource('quiz', QuizController::class);
        Route::resource('announcement', AnnouncementController::class);
        Route::resource('course-enroll', CourseEnrollController::class);
        Route::resource('send-email', EmailController::class);


        Route::resource('send-sms', SmsController::class);
        Route::resource('activity-log', StudentLogController::class);
        Route::resource('student-payment', StudenPaymentController::class);
        Route::get('payment-details/{student_id}/{course_id}', [StudenPaymentController::class, 'details'])->name('pay_details');


        Route::get('import-user', [UserManageController::class, 'import'])->name('import_user');
        Route::post('import-users', [UserManageController::class, 'importUsers'])->name('import.users');
        Route::get('promo-code', [CourseController::class, 'pindex'])->name('promo_index');
        Route::get('promo-code-create', [CourseController::class, 'pcreate'])->name('promo_create');


        Route::post('promo-code', [CourseController::class, 'pstore'])->name('promo_store');
        Route::get('promo-code/{id}', [CourseController::class, 'pedit'])->name('promo_edit');
        Route::PATCH('promo-code/{id}', [CourseController::class, 'pupdate'])->name('promo_update');



        Route::get('/slack/channel/create', [SlackController::class, 'channelCreate'])->name('channel_route_create');
        Route::get('/slack/channel', [SlackController::class, 'channelList'])->name('channel_route');
        Route::resource('student-exam', StudentExamController::class);
        Route::resource('student-quiz', StudentQuizController::class);


        Route::get('certificate-student', [StudentCertificateController::class, 'index'])->name('get_certificate');
        Route::get('certificate-student-quiz', [StudentCertificateController::class, 'indexQuiz'])->name('get_quiz');

resources/views/dashboard/video_record/create.blade.php
@extends('layouts.app')
@section('title') Teacher @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Video</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h4 class="mt-3 mb-3">Create Video</h4>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form action="{{ route('record-video.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf

                         <div class="row">

                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Course:</strong>
                                    <select class="form-control" name="course_id" required>
                                        <option value="">Select Course</option>
                                        @foreach($course as $c)
                                         <option value="{{$c->id}}">{{$c->course_title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Video Title:</strong>
                                    <input type="text" class="form-control" name="video_title" required>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Video:</strong>
                                    <input type="file" class="form-control" name="video" accept="video/*">
                                </div>
                            </div>

                            {{-- <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Video Url:</strong>
                                    <input type="text" class="form-control" name="video_url" required>
                                </div>
                            </div> --}}

                            <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
                                <div class="form-group">
                                    <strong>Recording Date: <span style="color:red">*</span></strong>
                                    <input type="datetime-local" name="publish_date" class="form-control" placeholder="Expire date" required>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3 mb-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dashboard/video_record/edit.blade.php
@extends('layouts.app')
@section('title') Teacher @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Video</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="card">
            <div class="row">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <h4 class="mt-3 mb-3">Create Video</h4>
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong> There were some problems with your input.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    <form action="{{ route('record-video.update',$video->id) }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        {{method_field('PATCH')}}

                         <div class="row">

                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Course:</strong>
                                    <select class="form-control" name="course_id" required>
                                        <option value="">Select Course</option>
                                        @foreach($course as $c)
                                         <option value="{{$c->id}}" @if($video->course_id==$c->id) selected @endif>{{$c->course_title}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <div class="form-group">
                                    <strong>Video Title:</strong>
                                    <input type="text" class="form-control" value="{{$video->video_title}}" name="video_title" required>
                                </div>
                            </div>


                            <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <video width="420" height="200" controls>
                                    <source src="{{asset('dashboard/record_video/'.$video->video_path)}}" type="video/mp4">

                                    </video>
                                <div class="form-group">
                                    <strong>Video:</strong>
                                    <input type="file" class="form-control" name="video" accept="video/*">
                                </div>
                            </div>

                            {{-- <div class="col-xs-12 col-sm-12 col-md-12 mb-2">
                                <a target="_blank" href="{{$video->video_url}}">View Video</a>

                                <div class="form-group">
                                    <strong>Video Url:</strong>
                                    <input type="text" value="{{$video->video_url}}" class="form-control" name="video_url" required>
                                </div>
                            </div> --}}

                            <div class="col-xs-12 col-sm-12 col-md-12 mt-2">
                                <div class="form-group">
                                    <strong>Recording Date: <span style="color:red">*</span></strong>
                                    <input type="datetime-local" value="{{$video->publish_date}}" name="publish_date" class="form-control" placeholder="Expire date" required>
                                </div>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 mt-3 mb-3">
                                    <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>
      </div>
    </section>
  </div>
@endsection

resources/views/dashboard/video_record/index.blade.php
@extends('layouts.app')
@section('title') Teacher @endsection
@section('content')
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0"></h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Video List</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>

    <section class="content">
      <div class="container-fluid">
         @if(session()->has('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
         @endif

         <table class="table table-bordered data-table">
                <thead>
                    <tr>
                        <th>Sl</th>
                        <th>Video</th>
                        <th>Video Title</th>
                        <th>Video Link</th>
                        <th>Publish date</th>
                        <th width="100px">Action</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
      </div>
    </section>
  </div>

  @section('script')

  <script>
    $(document).ready(function() {
               $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('record-video.index') }}",
                columns: [
                    {
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex',
                },
                {data: 'video', name: 'video'},
                {data: 'video_title', name: 'video_title'},
                {data: 'video_link', name: 'video_link'},
                {data: 'publish_date', name: 'publish_date'},
                {data: 'action', name: 'action', orderable: false, searchable: false},
                ]
            });
        });
  </script>
  @endsection
@endsection